/***************************************************************************//**
* \file TEST_MODEL_ifx_y_data_float.c
*
* \brief
* Autogenerated with ml-coretools, this file contains output data
* for the TEST_MODEL model in float representation.
* Date: 2023-02-09 09:55:07.152758
*******************************************************************************
* \copyright
* Copyright 2023, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#include "TEST_MODEL_ifx_y_data_float.h"


const unsigned char TEST_MODEL_y_data_bin[] __attribute__((aligned(4))) = {
  0x2a, 0x6b, 0xa3, 0x38, 0xe4, 0xfa, 0x7f, 0x3f
};
